In [1]:
import requests
import json

import pandas as pd

file = "winemag-data-130k-v2.csv"
### read data files into Data Frame
wine_df = pd.read_csv(file, index_col = 0)

In [2]:
wine_df.head(5)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
id,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
## drop all region_1 = NaN
wine_df = wine_df.dropna(subset=["region_1"])

In [4]:
## verify there are no more region_1 as Nan
wine_df[wine_df["region_1"]== "NaN"]

Empty DataFrame
Columns: [country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

In [5]:
loc_df = pd.read_csv("region_data_new.csv")

In [7]:
loc_df.head(5)

              region_1 country   latitude   longitude
0                 Etna   Italy  37.751005   14.993435
1    Willamette Valley      US  44.942554 -122.933762
2  Lake Michigan Shore      US  43.834810  -85.072029
3               Alsace  France  48.318179    7.441624
4          Napa Valley      US  38.502469 -122.265389

In [ ]:
lat = []
lng = []
for index, row in wine_df.iterrows():
    for j, r in loc_df.iterrows():
        if(row.region_1 == r.region_1):
            lat.append(r.latitude)
            lng.append(r.longitude)